### ISSUE TITLE
Adding Suspend

### ISSUE THREAD

**Issue by zgrimshell** [neumann-d/ShutdownTimer#15]
It would be nice to add suspend mode so if someone doesn't want to shutdown (geeks don't like shutting down their laptops but to suspend them) :)

**Comment by neumann89** [comment]
Thanks, good point. It should not be very complex too implement.

**Comment by zgrimshell** [comment]
Indeed. Using dbus to send suspend command so you don't need to use root (and it will also lock screen upon resume if that is set).

**Comment by neumann89** [comment]
I've created a extension for suspend mode similar to this one: https://github.com/neumann89/SuspendTimer 
I will upload it to https://extensions.gnome.org soon.

**Comment by tylla** [comment]
If I may add my thoughts, the best would be to add a "shutdown action" option, so one can choose from shutdown/restart/suspend/hibernate.
Maybe a fifth option "use system power button setting" could go there as well.

**Comment by neumann-d** [comment]
Suspend added in 777a1ca847119fa0ee8832088924e723234552e1
Feel free to add a restart function and change the suspend toggle option to a dropdown or radio menu
