### ISSUE TITLE
Error No JS module 'tweener' found in Gnome 3.38

### ISSUE THREAD

**Issue by squall77it** [neumann-d/ShutdownTimer#37]
The extension does not work anymore on Gnome 3.38, with the error: "JS ERROR: Extension ShutdownTimer@neumann: ImportError: No JS module 'tweener' found in search path".
I have fixed it with this pull request #36.

**Comment by neumann-d** [comment]
Fixed by https://github.com/neumann-d/ShutdownTimer/pull/36
