### ISSUE TITLE
So many features

### ISSUE THREAD

**Issue by Deminder** [neumann-d/ShutdownTimer#40]
Hey,

I have spend some time learning how to write gnome-shell extensions with your nifty extension and added some features I personally wanted. [Deminder/ShutdownTimer](https://github.com/Deminder/ShutdownTimer)
~~If you want, I would try to make pull requests for features you like to see.
Not everything is easily extractable but hopefully you just want them all :smile:~~

Thanks for writing this extension! :+1: 

![Screenshot](https://raw.githubusercontent.com/Deminder/ShutdownTimer/master/data/img/screenshot.png)

# Features
- Timer for _Poweroff_, _Reboot_, _Suspend_

  - Options may be reordered or hidden
  - Disabling the extension leaves a timer process alive. The extension is only completely disabled if the screen saver does not activate within three seconds.

- Show scheduled shutdown info as _(sys)_

  - Fetched from `/run/systemd/shutdown/scheduled`
  - Externally run `shutdown 100` displayed in menu: <br/>![externalScheduleMenu](https://raw.githubusercontent.com/Deminder/ShutdownTimer/master/data/img/externalScheduleFeature.png)
  - Displays the more urgent (external or interal) timer

- Install privileged control script: `shutdowntimerctl`

  - Control `rtcwake` and `shutdown` as user

- Wake alarm

  - Set a real-time-clock (rtc) alarm which wakes the system after shutdown
  - Wake info from: `/sys/class/rtc/rtc0/wakealarm`
  - Wake info displayed in menu: <br/>![wakeInfoMenu](https://raw.githubusercontent.com/Deminder/ShutdownTimer/master/data/img/wakeInfoFeature.png)
  - Controlling wake alarm requires installation of privileged script
  - Note: for advanced use-cases there are more suitable tools: e.g. [gnome-schedule](https://gitlab.gnome.org/GNOME/gnome-schedule)

- Root shutdown protection

  - Toggle `shutdown ${REQUESTED_MINUTES + 1}` command with shutdown timer (for _Poweroff_ and _Reboot_)
  - Protection against gnome-shell terminating, e.g., when logging out
  - If privileged script is not installed, `shutdown` command is run as user

- Check command
  - Runs a shell command and will only continue shutdown if command succeeds
  - Check command may be canceled

# Small changes
- Delay `showTextbox` animation ( problem: not able to read messages with faster animation-speed configured )
- Timer uses `GLib.DateTime`
- Toggle of switcher does not cause popup to close
- Disable toggle when timer is done

* restructure like [just-perfection](https://gitlab.gnome.org/jrahmatzadeh/just-perfection)
* build zip with Makefile
* includes (#43 )

# Problems
- Translations are adjusted but very incomplete (except for German)
- `"shell-version": ["3.36", "3.38", "40"]`

**Comment by neumann-d** [comment]
Hi @Deminder 
Thank you for sharing your improvements to this extension! I will definitely checkout your extension and looking forward to merge your new features.

**Comment by Deminder** [comment]
Hi @neumann-d, nice too hear :+1:
my previous version was rejected because of the user writable `pkexec` call for the rootmode.
Now a privileged `shutdowntimerctl` tool is installed for the user instead.
Extracting features does not make sense anymore (too much has changed). It would be best if all changes make it too your repo. 
I would make a pull request with `ShutdownTimer@Deminder` replaced again with `ShutdownTimer@neumann` if you decide you want it all :smile:

**Comment by neumann-d** [comment]
As I mentioned in your PR #47 , I've added a link on top of this README to checkout your extension with all the great features.
