### ISSUE TITLE
Gnome 41 support

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [neumann-d/ShutdownTimer#48]
Firstly, thank you for the nice gnome extension.

Currently, gnome shell is v41, but the extension seems to only support v40. Could you add support for v41, please?

**Comment by neumann-d** [comment]
Thanks for the feedback @ChristophSchmidpeter!
GNOME shell v41 is supported now in the latest release.

**Comment by ChristophSchmidpeter** [comment]
Thanks!
